askflask/homepage/routes.py
from flask import render_template, request, redirect, url_for, flash, Response, Blueprint
from flask_mongoengine import MongoEngine
from flask_login import LoginManager, current_user, login_user, logout_user, login_required
from flask_bcrypt import Bcrypt
from werkzeug.utils import secure_filename
import random

# stdlib

# local
from datetime import datetime

# local
from .. import app, bcrypt, client
from .forms import (SearchForm)
from ..models import User, Question, load_user, Answers, LikedPosts
from ..utils import current_time


homepage= Blueprint('homepage', __name__)
""" ************ View functions ************ """

@homepage.route('/', methods=['GET', 'POST'])
def index():
    form = SearchForm()
    qu=Question.objects()
    arr=[]
    arr1=[]
   
    for i in range(len(Question.objects())):
       arr.append(qu.next())
    for i in range(10):
        if len(arr) > 0:
            x=random.choice(arr)
            if x not in arr1:
                arr1.append(x)
            else:
                i=i-1
    if form.validate_on_submit():
        return redirect(url_for('homepage.question_results', question=form.search_query.data))
    arr1.sort(key=lambda x: x.likes, reverse=True)
    return render_template('index.html', form=form, questions=arr1)

@homepage.route('/search-results/<question>', methods=['GET'])
def question_results(question):

    results = Question.objects(content=question)

    if len(results) == 0:
        return render_template('query.html', error_msg='This question does not exit! Would you like to ask it? Click here!')
    
    return redirect(url_for('questionpage.questionAnswered', questionAsked=question))  

@homepage.route('/groupMembers', methods=['GET'])
def groupMembers(): 
    return render_template('groupMembers.html')

askflask/loginpage/routes.py
from flask import render_template, request, redirect, url_for, flash, Response, Blueprint, session
from flask_mongoengine import MongoEngine
from flask_login import LoginManager, current_user, login_user, logout_user, login_required
from flask_bcrypt import Bcrypt
from werkzeug.utils import secure_filename
from flask_mail import Mail, Message
import requests
import pyotp
import qrcode
import qrcode.image.svg
from io import BytesIO
from wtforms import StringField, IntegerField, SubmitField, TextAreaField, PasswordField
from wtforms.validators import (InputRequired, DataRequired, NumberRange, Length, Email, 
                                EqualTo, ValidationError )
# stdlib

# local
from datetime import datetime

# local
from .. import app, bcrypt, client, mail
from .forms import (RegistrationForm, LoginForm, UpdateUsernameForm)
from ..models import User, Question, load_user, Answers
from ..utils import current_time




loginpage= Blueprint('loginpage', __name__)
""" ************ View functions ************ """

@loginpage.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('homepage.index'))

    form = RegistrationForm()
    if form.validate_on_submit():
        requests.Session()
        hashed = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        finalProjectUser = User(username=form.username.data, 
                    email=form.email.data, password=hashed)
        session['new_username'] = finalProjectUser  
        print('OTP secret:', finalProjectUser.otp_secret)
      
        finalProjectUser.save()
      
        flash('Please login')
        return redirect(url_for('loginpage.tfa'))
        
    return render_template('register.html', form=form)



@loginpage.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('homepage.index'))
    form = LoginForm()  


    if form.validate_on_submit():

        user = User.objects(username=form.username.data).first()
        if (user is not None and bcrypt.check_password_hash(user.password, form.password.data)):  
            
            login_user(user)        
           
            return redirect(url_for('homepage.index'))
        else:
             flash('Wrong username or password.')
    return render_template('login.html', form=form)

 

@loginpage.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('homepage.index'))

@loginpage.route('/account', methods=['GET', 'POST'])
@login_required
def account():
    
    form = UpdateUsernameForm()
    
    if form.validate_on_submit():
        if len(User.objects(username=form.username.data)) == 0:  
            current_user.modify(username=form.username.data)
            current_user.save()
           
            msg = Message("You changed your username!",
            recipients=User.objects(username=current_user.username).first().email.split())
            username= current_user.username
            msg.body = "You changed your username to "+username
            mail.send(msg)
            return redirect(url_for('loginpage.account'))           
        else:
            flash('This username is already taken!')                   
    return render_template('account.html', form=form, user=current_user)

@loginpage.route('/user/<username>')
def user_detail(username):
    user=load_user(username)
    if user is not None:
       
        return render_template('user_detail.html', user=username, questions= Question.objects(commenter=user.id), total=len(Question.objects(commenter=user.id)))
    return render_template('user_detail.html')

@loginpage.route("/tfa")
def tfa():
    if 'new_username' not in session:
        return redirect(url_for('homepage.index'))

    headers = {
        'Cache-Control': 'no-cache, no-store, must-revalidate',
        'Pragma': 'no-cache',
        'Expires': '0' # Expire immediately, so browser has to reverify everytime
    }

    return render_template('tfa.html'), headers

@loginpage.route("/qr_code")
def qr_code():
    if 'new_username' not in session:
        return redirect(url_for('homepage.index'))
   
    user = User.objects(username=session['new_username'].get("username")).first()
    session.pop('new_username')
    print('OTP secret:', user.otp_secret)
    uri = pyotp.totp.TOTP(user.otp_secret).provisioning_uri(name=user.username, issuer_name='AskFlask-2FA')
    img = qrcode.make(uri, image_factory=qrcode.image.svg.SvgPathImage)
    stream = BytesIO()
    img.save(stream)

    headers = {
        'Content-Type': 'image/svg+xml',
        'Cache-Control': 'no-cache, no-store, must-revalidate',
        'Pragma': 'no-cache',
        'Expires': '0' # Expire immediately, so browser has to reverify everytime
    }

    return stream.getvalue(), headers

askflask/questionpage/routes.py
from flask import render_template, request, redirect, url_for, flash, Response, Blueprint, session
from flask_mongoengine import MongoEngine
from flask_login import LoginManager, current_user, login_user, logout_user, login_required
from flask_bcrypt import Bcrypt
from werkzeug.utils import secure_filename
from flask_mail import Mail, Message
import requests
import pyotp
import qrcode
import qrcode.image.svg
from io import BytesIO
from wtforms import StringField, IntegerField, SubmitField, TextAreaField, PasswordField
from wtforms.validators import (InputRequired, DataRequired, NumberRange, Length, Email, 
                                EqualTo, ValidationError )
# stdlib
from datetime import datetime

# local
from .. import app, bcrypt, client, mail
from .forms import (QuestionForm, QuestionAnsweredForm, LikeForm)
from ..models import User, Question, load_user, Answers, LikedPosts
from ..utils import current_time

questionpage=Blueprint('questionpage', __name__)

@questionpage.route('/questionAsk', methods=['GET', 'POST'])
@login_required
def questionAsk():

    form = QuestionForm()
    
    if form.validate_on_submit():    
        questionContent=form.text.data
        
        if len(Question.objects(question_id=questionContent)) == 0:
            
            question = Question(
      
                commenter=load_user(current_user.username), 
                content=questionContent, 
                date=current_time(),
                question_id=form.text.data,
                likes=0,
             )
        
            question.save()

            return redirect(url_for('questionpage.questionAnswered', questionAsked=form.text.data))
        else:
            flash('Question Already Asked! Ask a different question or click here to view the question\'s page!')
            #if you have time you could link em to the question
            
            return render_template('questionAsk.html', form=form, question=questionContent)
    return render_template('questionAsk.html', form=form)

@questionpage.route('/questionAnswered/<questionAsked>', methods=['GET', 'POST'])
def questionAnswered(questionAsked):
   
    form= QuestionAnsweredForm()
    if form.validate_on_submit(): 
      
        answer = Answers(  
            answer=form.text.data,
            date=current_time(),
            question_id=questionAsked,
            commenter=load_user(current_user.username), 
         
        )
        username= Question.objects(question_id=questionAsked).first().commenter
       
        if(current_user.username != username.username):
         
            username= Question.objects(question_id=questionAsked).first().commenter
           
            msg = Message("Someone answered your question!",
                 recipients=username.email.split())
            
            msg.body = current_user.username+" answered your question!"
            mail.send(msg)
        
        answer.save()

        return redirect(url_for('questionpage.questionAnswered', questionAsked=questionAsked))
    form1= LikeForm()
    if form1.validate_on_submit():
        y=0
        qu=Question.objects(question_id=questionAsked)
      
        if qu.first().likes!=0:
            lp=LikedPosts.objects()
            for i in range(len(LikedPosts.objects())):
                x= lp.next()
            
               
          
            
                if x.question_id == questionAsked and current_user.username == x.liker:
                     y=1
                    
        if y==0:
            thisliker=LikedPosts(
                liker=current_user.username,
                question_id=questionAsked,
            )
            thisliker.save()
         
            prevLikes=Question.objects(question_id=questionAsked).first().likes
            numOfLikes=Question.objects(question_id=questionAsked).first().modify(likes=prevLikes+1)
           
        return redirect(url_for('questionpage.questionAnswered', questionAsked=questionAsked))
    answers = Answers.objects(question_id=questionAsked)
   
    return render_template('questionAnswered.html', form=form, form1=form1, question=questionAsked,numlikes=Question.objects(question_id=questionAsked).first().likes, answers=answers)

@questionpage.route('/allQuestions', methods=['GET', 'POST'])
def allQuestions():
    arr=[]
    for i in Question.objects():
        arr.append(i)
    arr.sort(key=lambda x: x.likes, reverse=True)
    return render_template('allQuestions.html', questions=arr)

askflask/templates/account.html
{% extends "header.html" %}
{% block content %}

<div class="row">
    <div class="col">
        
        {# Greeting #}
     
        <h2>Welcome to your account {{user.username}}!</h2>
    </div>
</div>
<div class="row">
    <div class="col">
        {# Username Update Form #}
       
        <form method="POST" action="">
            {{ form.csrf_token }}
            <h3>Do you want to change your username!</h3>
            <div class="form-group">
        {{ form.username(class="form-control", placeholder="Enter your new username") }}
            </div>
        <div class="form-group">
        {{ form.submit(class="form-control") }}
        <br /> 
        <span class="float-left">
            {% with messages = get_flashed_messages() %}
            {% if messages %}
              {% for message in messages %}
                <small>{{ message }}</small> 
              {% endfor %}
            {% endif %}
          {% endwith %}
        </span>
            </div>
        </form>
    </div>
</div>
<div class="row">
    <div class="col">
        {# EXTRA CREDIT #}
        {# Profile Picture Update Form #}
    </div>
</div>
<div class="row">
    <div class="col">
        {# Link to see all of the current user's reviews. #}
        <a href="{{ url_for('loginpage.user_detail', username=user.username) }}"><b> Want to see all your questions! </b></a>
    </div>
</div>

{% endblock %}

askflask/templates/allQuestions.html
{% extends "header.html" %}
{% block content %}

{% for q in questions %}
        <h3> {{q.date}}
        ❤ <b>{{ q.likes }} <span>&#183;</span></b>
        <a href="{{ url_for('questionpage.questionAnswered', questionAsked=q.content) }}"><b>{{ q.content }} </b></a></h3>
            <br>
          {% endfor %}

{% endblock %}

askflask/templates/base.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
     <link rel="stylesheet" href="{{ url_for('static', filename='custom.css') }}">
    {% if title %}
        <title>{{ title }}</title>
    {% else %}
        <title>AskFlask</title>
    {% endif %}
</head>
<body>
    {% block header %}
    <h1>Overrideable Content</h1>
    {% endblock %}

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

askflask/templates/groupMembers.html
<h1>Group members: Mark Hopkins</h1>

askflask/templates/header.html
{% extends "base.html" %}
{% block header %}
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <a class="navbar-brand" href="{{ url_for('homepage.index') }}">AskFlask</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav ml-auto">
            {% if current_user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('loginpage.account') }}">
                    Account
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('loginpage.logout') }}">
                    Logout
                </a>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('loginpage.login') }}">
                    Login
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('loginpage.register') }}">
                    Make an account
                </a>
            </li>
            {% endif %}
        </ul>
    </div>
</nav>


<div class="container">
    {% block content %}{% endblock %}
</div>
{% endblock %}

askflask/templates/index.html
{% extends "header.html" %}
{% block content %}

<div class="row">
    <div class="col">
        <a href="{{ url_for('questionpage.questionAsk') }}"><b> Want to ask a question!?! </b></a>
        
        <br>You can also search for one!
    </div>
    <div class="col">
        <form action="/" class="form-inline my-2 my-lg-0" method="POST">
            {{ form.csrf_token }}
            {{ form.search_query(class="form-control", placeholder="Search for a question!") }}

            {% if form.search_query.errors %}
            <div class="alert alert-warning" role="alert">
                {% for error in form.search_query.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% endif %}

            {{ form.submit(class="btn btn-outline-success") }}
        </form>
    </div>
    
    <div>
        <h3>ASK ANY QUESTION OR VIEW ANY ANSWER! Take a look at these questions below! </h3>
        {% for q in questions %}
        <h3> {{q.date}}
        ❤ <b>{{ q.likes }} <span>&#183;</span></b>
        <a href="{{ url_for('questionpage.questionAnswered', questionAsked=q.content) }}"><b>{{ q.content }} </b></a></h3>
     

    
            <br>
          {% endfor %}
         <b>Would you like to see all of the questions? <a href="{{ url_for('questionpage.allQuestions') }}">{{ "Click here!" }} </a></b>
         <br>
         <a href="{{ url_for('homepage.groupMembers') }}"><b> Link to all group members.</b></a>
    </div>
</div>
{% endblock %}

askflask/templates/login.html
{% extends "header.html" %}
{% block content %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<div class="row">
    <div class="col">
        
        <h2>Log In</h2>
        <span class="float-left">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
          {% for message in messages %}
            <small>{{ message }}</small> 
          {% endfor %}
        {% endif %}
      {% endwith %}
    </span>
    <br />
        <form method="POST" action="">
            {{ form.csrf_token }}
            <div class="form-group">
                <div class="form-group">
        {{ form.username(class="form-control", placeholder="Enter Username") }}
        {% if form.username.errors %}
        <span class="alert alert-warning">
          {% for error in form.username.errors %}
          
          <small>{{ error }}</small>
          
           {% endfor %}
           </span>
           {% endif %}
        </div>
        <div class="form-group">
        {{ form.password(class="form-control", placeholder="Enter Password" )}}
        {% if form.password.errors %}
        <span class="alert alert-warning" role="alert">
            {% for error in form.password.errors %}
    
              <small>{{ error }}</small>
               {% endfor %}
              </span>
              {% endif %}   
        </div>
        <div class="form-group">
       
            {{ form.token(class="form-control", placeholder="Enter 6 digit token")}} 
            {% if form.token.errors %}
        <span class="alert alert-warning" role="alert">
            {% for error in form.token.errors %}
    
              <small>{{ error }}</small>
               {% endfor %}
              </span>
              {% endif %}   
    
            </div>
        <div class="form-group">
       
        {{ form.submit(class="form-control")}} 

            </div>
     
            </div>
        </form>
    </div>
</div>
<div class="row">
    <div class="col">
        {# Add link to redirect users to Registration page if they don't have an account #}
        <a href="{{ url_for('loginpage.register') }}"><b> Don't have and account make one here! </b></a>
    </div>
</div>

{% endblock %}

askflask/templates/query.html
{% extends "header.html" %}
{% block content %}
{% if error_msg %}
    <p> <a href="{{ url_for('questionpage.questionAsk') }}"><b>{{error_msg}}</b></a> </p>
{% endif %}


{% endblock %}

askflask/templates/questionAnswered.html
{% extends "header.html" %}
{% block content %}

{% if error_msg %}
<b>{{ error_msg }}</b>
{% endif %}



<div class="row">
  <div class="col">
    <div class="text-left">
      <h1>Question that was asked was:</h1> 
      <h2>{{question.content}}</h2>
      
      <form method="POST" action="">
        {{ form.csrf_token }}
        <h2>{{question}}</h2>
        
        <div class="row">
          <div class="col">
            <form method="POST" action="">
       
              <div class="form-group">
                <h1><small class="float-right">❤  <b><span>&#183;</span> {{ numlikes }}  {% if numlikes == 1 %} like! {% else %} likes! {%endif%}</b></small></h1>
                {% if current_user.is_authenticated %}
                {{ form.csrf_token }}
                {{form1.like()}}
              </form>
            </div>
          </div>
          {% endif %}
        <div class="form-group">
            <div class="form-group">
           
    
    {% with messages = get_flashed_messages() %}
            {% if messages %}
              {% for message in messages %}
                <large>{{ message }}</large> 
              {% endfor %}
            {% endif %}
          {% endwith %}
    </div>
  
    <div class="form-group">
   
    
        </div>
        
        </div>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <h1> All Answers <small class="float-right">{{ answers.count() }} Answers for this question!</small></h1>
    <ul class="media-list">
      {% for answer in answers %}
    
      <li class="media review-item">
        <div class="media-body">
          <span class="float-right">
            <small>{{ answer.date }}</small>
          </span>
          <a href="{{ url_for('loginpage.user_detail', username=answer.commenter.username) }}">
            <strong>@{{ answer.commenter.username }}</strong>
          </a>
          <p>
           
            {{ answer.answer }}
          </p>
        </div>
      </li>
   
      {% endfor %}
    </ul>
  </div>
</div>

{% if current_user.is_authenticated %}

<div class="row">
  <div class="col">
    <form method="POST" action="">
      {{ form.csrf_token }}
      <div class="form-group">
        {{ form.text.label }}
        {{ form.text(class="form-control") }}
       
        {% if form.text.errors %}
        <div class="alert alert-warning" role="alert">
          {% for error in form.text.errors %}
          <span>{{ error }}</span>
          {% endfor %}
        </div>
        {% endif %}

      </div>
      {{ form.submit() }}
    </form>
  </div>
</div>
{% endif %}


{% endblock content %}

askflask/templates/questionAsk.html
{% extends "header.html" %}
{% block content %}

{% if error_msg %}
<b>{{ error_msg }}</b>
{% endif %}



<div class="row">
  <div class="col">
    <div class="text-left">
      <h1>ASK A QUESTION</h1>
      <form method="POST" action="">
        {{ form.csrf_token }}
        
        <div class="form-group">
            <div class="form-group">
              
    {{ form.text(class="form-control") }}
    {% with messages = get_flashed_messages() %}
            {% if messages %}
              {% for message in messages %}
                <large><a href="{{ url_for('questionpage.questionAnswered', questionAsked=question) }}">{{message}}</a>  </large> 
              {% endfor %}
            {% endif %}
          {% endwith %}
    </div>
  
    <div class="form-group">
    {{ form.submit(class="form-control")}} 
    
    
        </div>
        
        </div>
      </div>
    </div>
  </div>
</div>
{#

<div class="row">
  <div class="col-md-12">
    <h1> Reviews <small class="float-right">{{ reviews.count() }} reviews</small></h1>
    <ul class="media-list">
      {% for review in reviews %}
      <li class="media review-item">
        <div class="media-body">
          <span class="float-right">
            <small>{{ review.date }}</small>
          </span>
          <a href="{{ url_for('user_detail', username=review.commenter.username) }}">
            <strong>@{{ review.commenter.username }}</strong>
          </a>
          <p>
            {{ review.content }}
          </p>
        </div>
      </li>
      {% endfor %}
    </ul>
  </div>
</div>

{% if current_user.is_authenticated %}

<div class="row">
  <div class="col">
    <form method="POST" action="">
      {{ form.csrf_token }}
      <div class="form-group">
        {{ form.text.label }}
        {{ form.text(class="form-control") }}

        {% if form.text.errors %}
        <div class="alert alert-warning" role="alert">
          {% for error in form.text.errors %}
          <span>{{ error }}</span>
          {% endfor %}
        </div>
        {% endif %}

      </div>
      {{ form.submit() }}
    </form>
  </div>
</div>
{% endif %}
{% endif %}
#}
{% endblock content %}

askflask/templates/register.html
{% extends "header.html" %}
{% block content %}
<div class="row">
    <div class="col">
        <h2>Account Registration</h2>
        <h5>Passwords must at least include 1 uppercase letter and at least one symbol such as (@,$,&,or #)</h5>
    </div>
</div>
<div class="row">
    <div class="col">
        {# Ask the user to login if they already have an account #}
        <a href="{{ url_for('loginpage.login') }}"><b> Do you already have an account, LOG IN HERE! </b></a>
    </div>
</div>
<!-- Registration Form: -->
<div class="row">
    <div class="col">
        {# Optionally show flashed messages if/when you need them,
            if an authentication or other similar error occurs #}
           
         
                <form method="POST" action="">
                    {{ form.csrf_token }}
                    <div class="form-group">       
                        {{ form.username(class="form-control", placeholder="Username") }}
                        {% if form.username.errors %}
                      <span class="alert alert-warning">
                        {% for error in form.username.errors %}
                        
                        <small>{{ error }}</small>
                        
                         {% endfor %}
                         </span>
                         {% endif %}
                        </div>
                        <div class="form-group"> 
          {{ form.email(class="form-control", placeholder="Email")}}
                        {% if form.email.errors %}
                        <span class="alert alert-warning" role="alert">
                       {% for error in form.email.errors %}
                         <small>{{ error }}</small>
                          {% endfor %}
                         </span>
                         {% endif %}
                        </div>
                        <div class="form-group"> 
        {{ form.password(class="form-control", placeholder="Password") }}
        {% if form.password.errors %}
        <span class="alert alert-warning" role="alert">
            {% for error in form.password.errors %}
    
              <small>{{ error }}</small>
               {% endfor %}
              </span>
              {% endif %}   
                        </div>
        <div class="form-group"> 
        {{ form.confirm_password(class="form-control", placeholder="Confirm password")}}
 
        {% if form.confirm_password.errors %}
        <span class="alert alert-warning" role="alert">
       {% for error in form.confirm_password.errors %}
         <small>{{ error }}</small>
          {% endfor %}
         </span>
         {% endif %}
        </div>
        {{ form.submit(class="form-control")}} 
        
       
    </div>
      
</form>
    
    </div>
</div>

{% endblock %}

askflask/templates/tfa.html
{% extends "header.html" %}
{% block content %}
    <div>
        <h2>Two-Factor Auth Enrollment</h2>
    </div>
    <div>
        This website requires mandatory 2FA enrollment. 
    </div>
    <!-- Registration Form: -->
    <p>
        Use a authenticator app to enroll with us! You will need to use this app to login in the future.
    </p>
    <img src={{ url_for('loginpage.qr_code') }} alt="QR Code for 2FA">

    <div>
        When you're done, you can go to the <a href={{ url_for('loginpage.login') }}>Login page</a>!
    </div>

{% endblock %}

askflask/templates/user_detail.html
{% extends "header.html" %}
{% block content %}
<div class="row">
    <div class="col">
        {# Display any error messages #}
    </div>
</div>
<div class="row">
    <div class="col">
        {# Indicate which user's reviews we're looking at #}
        {% if user!=NULL %}
        <h1>{{user}}'s Questions!</h1>
        {% endif %}
        {% if user==NULL %}
        <h1>THIS USER DOESN'T EXIST!</h1>
        {% endif %}
    </div>
</div>
<div class="row">
    <div class="col">
       
        <span class="float-right">
            <p class="font-weight-bold">
               Total Questions Asked: {{total}}
            </p>
            
        </span>
        <br />
        <br />
        {% for question in questions %}
      <li class="media review-item">
        <div class="media-body">
          <span class="float-right">
            <small>{{ question.date }}</small>
          </span>
          <p>
            <p class="font-weight-bold">
                <a href="{{ url_for('questionpage.questionAnswered', questionAsked=question.content) }}">{{question.content}}</a>
            </p>
         
       
          </p>
        </div>
      </li>
      {% endfor %}
    </div>
</div>
{% endblock %}